version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
     coatl-dev-workflows:
        patterns:
          - "coatl-dev/workflows/*"
    labels: ["dependencies"]
    commit-message:
      prefix: "ci"
      include: "scope"
