version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels: ["gh-dependencies"]

  - package-ecosystem: "pip"
    directory: "/requirements"
    schedule:
      interval: "monthly"
    labels: ["pip-dependencies"]
    commit-message:
      prefix: "pip"
