name: pr-build

on:
  pull_request:
    branches:
      - 'coatl'
    paths:
      - '.github/workflows/pr-build.yml'
      - 'Dockerfile'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
